import Foundation

/// Configuration for generated Comet request source.
public struct OpenAPIGeneratorConfiguration: Sendable, Hashable {
  public var accessModifier: String
  public var imports: [String]
  public var includeHeaderComment: Bool

  public init(
    accessModifier: String = "public",
    imports: [String] = ["Foundation", "HTTPTypes", "Comet"],
    includeHeaderComment: Bool = true
  ) {
    self.accessModifier = accessModifier
    self.imports = imports
    self.includeHeaderComment = includeHeaderComment
  }
}

/// A focused JSON OpenAPI generator for Comet request types.
public struct OpenAPIGenerator: Sendable {
  public init() {}

  public func generate(
    data: Data,
    configuration: OpenAPIGeneratorConfiguration = OpenAPIGeneratorConfiguration()
  ) throws -> String {
    do {
      let document = try JSONDecoder().decode(OpenAPIDocument.self, from: data)
      return try self.generate(document: document, configuration: configuration)
    } catch let error as OpenAPIGeneratorError {
      throw error
    } catch {
      throw OpenAPIGeneratorError.invalidDocument("Unable to decode OpenAPI JSON: \(error)")
    }
  }

  public func generate(
    jsonString: String,
    configuration: OpenAPIGeneratorConfiguration = OpenAPIGeneratorConfiguration()
  ) throws -> String {
    guard let data = jsonString.data(using: .utf8) else {
      throw OpenAPIGeneratorError.invalidDocument("Unable to encode input as UTF-8.")
    }
    return try self.generate(data: data, configuration: configuration)
  }

  private func generate(
    document: OpenAPIDocument,
    configuration: OpenAPIGeneratorConfiguration
  ) throws -> String {
    let componentSchemas = document.components?.schemas ?? [:]
    let models = try componentSchemas.keys.sorted().map { name in
      try GeneratedSchemaModel(
        name: name,
        schema: componentSchemas[name]!,
        components: componentSchemas,
        accessModifier: configuration.accessModifier
      )
    }
    var operations: [GeneratedOperation] = []

    for path in document.paths.keys.sorted() {
      guard let item = document.paths[path] else { continue }
      for method in HTTPMethodName.allCases {
        guard let operation = item.operation(for: method) else { continue }
        operations.append(
          try GeneratedOperation(
            path: path,
            method: method,
            operation: operation,
            inheritedParameters: item.parameters,
            components: componentSchemas,
            accessModifier: configuration.accessModifier
          )
        )
      }
    }

    guard !operations.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument("The OpenAPI document did not contain any supported path operations.")
    }

    let duplicateTypeNames = Dictionary(grouping: operations, by: \.typeName)
      .filter { $0.value.count > 1 }
      .map(\.key)
      .sorted()
    guard duplicateTypeNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "Multiple operations generate duplicate request type names: \(duplicateTypeNames.joined(separator: ", "))."
      )
    }
    let duplicateModelNames = Dictionary(grouping: models, by: \.typeName)
      .filter { $0.value.count > 1 }
      .map(\.key)
      .sorted()
    guard duplicateModelNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "Multiple component schemas generate duplicate Swift type names: \(duplicateModelNames.joined(separator: ", "))."
      )
    }
    let collidingNames = Set(models.map(\.typeName))
      .intersection(Set(operations.map(\.typeName)))
      .sorted()
    guard collidingNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "Component schemas and operations generate duplicate Swift type names: \(collidingNames.joined(separator: ", "))."
      )
    }

    var lines: [String] = []
    if configuration.includeHeaderComment {
      lines.append("// Generated by comet-openapi-generate. Edit the OpenAPI source instead of this file.")
      lines.append("")
    }

    for module in configuration.imports {
      lines.append("import \(module)")
    }
    lines.append("")

    let generatedBlocks = try models.map { try $0.renderedLines() } + operations.map { $0.renderedLines() }
    for (index, block) in generatedBlocks.enumerated() {
      if index > 0 {
        lines.append("")
      }
      lines.append(contentsOf: block)
    }

    return lines.joined(separator: "\n") + "\n"
  }
}

/// Errors emitted by the OpenAPI generator.
public struct OpenAPIGeneratorError: Error, Sendable, CustomStringConvertible, Equatable {
  public var message: String

  public init(_ message: String) {
    self.message = message
  }

  public static func invalidDocument(_ message: String) -> Self {
    Self(message)
  }

  public static func unsupported(_ message: String) -> Self {
    Self("Unsupported OpenAPI feature: \(message)")
  }

  public var description: String {
    self.message
  }
}

private struct GeneratedOperation {
  let accessModifier: String
  let typeName: String
  let genericBodyType: Bool
  let bodyPayloadType: String?
  let method: HTTPMethodName
  let pathExpression: String
  let parameters: [GeneratedParameter]
  let queryParameters: [GeneratedParameter]
  let headerParameters: [GeneratedParameter]
  let hasJSONBody: Bool
  let responseType: String
  let responseSerializer: String
  let hasTypedErrorResponse: Bool
  let operationID: String

  init(
    path: String,
    method: HTTPMethodName,
    operation: OpenAPIOperation,
    inheritedParameters: [OpenAPIParameter],
    components: [String: OpenAPISchema],
    accessModifier: String
  ) throws {
    self.accessModifier = accessModifier
    self.method = method
    self.operationID = operation.operationID ?? "\(method.rawValue)-\(path)"
    self.typeName = Self.typeName(operationID: operation.operationID, method: method, path: path)

    let mergedParameters = Self.mergedParameters(
      inheritedParameters,
      overridingWith: operation.parameters
    )
    let parameters = try mergedParameters.map { try GeneratedParameter($0, components: components) }
    let duplicateSwiftParameterNames = Dictionary(grouping: parameters, by: \.swiftName)
      .filter { $0.value.count > 1 }
      .map(\.key)
      .sorted()
    guard duplicateSwiftParameterNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "\(self.operationID) has parameters that generate duplicate Swift names: \(duplicateSwiftParameterNames.joined(separator: ", "))."
      )
    }
    self.parameters = parameters
    self.queryParameters = parameters.filter { $0.location == .query }
    self.headerParameters = parameters.filter { $0.location == .header }
    self.pathExpression = try Self.pathExpression(path: path, parameters: parameters)

    if let requestBody = operation.requestBody {
      guard let jsonBody = requestBody.content["application/json"] else {
        throw OpenAPIGeneratorError.unsupported(
          "\(self.operationID) declares a request body without application/json content."
        )
      }
      self.hasJSONBody = true
      self.bodyPayloadType = try jsonBody.schema?.swiftType(
        components: components,
        inlineObjectFallback: nil
      )
      self.genericBodyType = self.bodyPayloadType == nil
    } else {
      self.hasJSONBody = false
      self.bodyPayloadType = nil
      self.genericBodyType = false
    }

    let response = try Self.successResponse(from: operation.responses, components: components)
    self.responseType = response.type
    self.responseSerializer = response.serializer
    self.hasTypedErrorResponse = operation.responses.contains { status, _ in
      guard let code = Int(status) else { return status == "default" }
      return !(200..<300).contains(code)
    }
  }

  func renderedLines() -> [String] {
    var lines: [String] = []
    let protocolName = self.hasTypedErrorResponse ? "APIRequestWithErrorResponse" : "APIRequest"
    let generic = self.genericBodyType ? "<Body: Encodable & Sendable>" : ""
    lines.append("\(self.accessModifier) struct \(self.typeName)\(generic): \(protocolName) {")
    lines.append("  \(self.accessModifier) typealias Response = \(self.responseType)")
    if self.hasTypedErrorResponse {
      lines.append("  \(self.accessModifier) typealias ErrorResponse = Data")
    }
    lines.append("")

    for parameter in self.parameters {
      lines.append("  \(self.accessModifier) let \(parameter.swiftName): \(parameter.swiftType)")
    }
    if self.hasJSONBody {
      lines.append("  \(self.accessModifier) let bodyPayload: \(self.bodyPayloadType ?? "Body")")
    }

    if !self.parameters.isEmpty || self.hasJSONBody {
      lines.append("")
      lines.append(contentsOf: self.initLines())
    } else {
      lines.append("")
      lines.append("  \(self.accessModifier) init() {}")
    }

    lines.append("")
    lines.append("  \(self.accessModifier) var path: Path {")
    lines.append("    \(self.pathExpression)")
    lines.append("  }")
    lines.append("")
    lines.append("  \(self.accessModifier) let method: HTTPMethod = \(self.method.swiftExpression)")

    if !self.queryParameters.isEmpty {
      lines.append("")
      lines.append("  \(self.accessModifier) var queryItems: [QueryItem] {")
      lines.append("    var items: [QueryItem] = []")
      for parameter in self.queryParameters {
        lines.append(contentsOf: parameter.queryItemLines())
      }
      lines.append("    return items")
      lines.append("  }")
    }

    if !self.headerParameters.isEmpty {
      lines.append("")
      lines.append("  \(self.accessModifier) var headers: HTTPFields {")
      lines.append("    var headers = HTTPFields()")
      for parameter in self.headerParameters {
        lines.append(contentsOf: parameter.headerLines())
      }
      lines.append("    return headers")
      lines.append("  }")
    }

    if self.hasJSONBody {
      lines.append("")
      lines.append("  \(self.accessModifier) var body: HTTPBody {")
      lines.append("    .json(self.bodyPayload)")
      lines.append("  }")
    }

    lines.append("")
    lines.append("  \(self.accessModifier) var options: RequestOptions {")
    lines.append("    RequestOptions(")
    lines.append("      metadata: RequestMetadata(operationID: \(self.operationID.swiftLiteral))")
    lines.append("    )")
    lines.append("  }")
    lines.append("")
    lines.append("  \(self.accessModifier) let responseSerializer: ResponseSerializer<\(self.responseType)> = \(self.responseSerializer)")

    if self.hasTypedErrorResponse {
      lines.append("  \(self.accessModifier) let errorResponseSerializer: ErrorResponseSerializer<Data> = .data")
    }

    lines.append("}")
    return lines
  }

  private func initLines() -> [String] {
    var lines: [String] = []
    lines.append("  \(self.accessModifier) init(")
    var arguments = self.parameters.map { parameter in
      "    \(parameter.swiftName): \(parameter.swiftType)"
    }
    if self.hasJSONBody {
      arguments.append("    bodyPayload: \(self.bodyPayloadType ?? "Body")")
    }
    for index in arguments.indices {
      lines.append(arguments[index] + (index == arguments.indices.last ? "" : ","))
    }
    lines.append("  ) {")
    for parameter in self.parameters {
      lines.append("    self.\(parameter.swiftName) = \(parameter.swiftName)")
    }
    if self.hasJSONBody {
      lines.append("    self.bodyPayload = bodyPayload")
    }
    lines.append("  }")
    return lines
  }

  private static func typeName(
    operationID: String?,
    method: HTTPMethodName,
    path: String
  ) -> String {
    let raw = operationID ?? "\(method.rawValue) \(path)"
    let name = raw.identifierWords().map(\.capitalized).joined()
    guard !name.isEmpty else { return "GeneratedRequest" }
    return "\(name.prefixedIfNeededForSwiftIdentifier(prefix: "Generated"))Request"
  }

  private static func pathExpression(
    path: String,
    parameters: [GeneratedParameter]
  ) throws -> String {
    let pathParameters = Dictionary(uniqueKeysWithValues: parameters.filter { $0.location == .path }.map { ($0.originalName, $0) })
    let segments = path
      .split(separator: "/")
      .map(String.init)
      .filter { !$0.isEmpty }

    guard !segments.isEmpty else { return "Path(\"\")" }

    var expressions: [String] = []
    for segment in segments {
      if segment.hasPrefix("{"), segment.hasSuffix("}") {
        let rawName = String(segment.dropFirst().dropLast())
        guard let parameter = pathParameters[rawName] else {
          throw OpenAPIGeneratorError.invalidDocument("Path parameter {\(rawName)} is missing from the operation parameters.")
        }
        expressions.append("self.\(parameter.swiftName)")
      } else {
        expressions.append(segment.swiftLiteral)
      }
    }

    let first = expressions.removeFirst()
    let base = first.hasPrefix("\"") ? first : "Path(\"\") / \(first)"
    guard !expressions.isEmpty else { return first.hasPrefix("\"") ? base : base }
    return ([base] + expressions).joined(separator: " / ")
  }

  private static func successResponse(
    from responses: [String: OpenAPIResponse],
    components: [String: OpenAPISchema]
  ) throws -> (type: String, serializer: String) {
    let success = responses
      .compactMap { status, response -> (Int, OpenAPIResponse)? in
        guard let code = Int(status), (200..<300).contains(code) else { return nil }
        return (code, response)
      }
      .sorted { $0.0 < $1.0 }
      .first

    guard let success else {
      return ("Data", ".data")
    }

    if success.0 == 204 || success.1.content.isEmpty {
      return ("EmptyResponse", ".empty")
    }

    if success.1.content.keys.contains("text/plain") {
      return ("String", ".string()")
    }

    if let schema = success.1.content["application/json"]?.schema,
       let type = try schema.swiftType(components: components, inlineObjectFallback: nil) {
      return (type, ".json(\(type).self)")
    }

    return ("Data", ".data")
  }

  private static func mergedParameters(
    _ inherited: [OpenAPIParameter],
    overridingWith operationParameters: [OpenAPIParameter]
  ) -> [OpenAPIParameter] {
    var parameters = inherited
    for operationParameter in operationParameters {
      if let index = parameters.firstIndex(where: {
        $0.name == operationParameter.name && $0.location == operationParameter.location
      }) {
        parameters[index] = operationParameter
      } else {
        parameters.append(operationParameter)
      }
    }
    return parameters
  }
}

private struct GeneratedSchemaModel {
  let accessModifier: String
  let originalName: String
  let typeName: String
  let schema: OpenAPISchema
  let components: [String: OpenAPISchema]

  init(
    name: String,
    schema: OpenAPISchema,
    components: [String: OpenAPISchema],
    accessModifier: String
  ) throws {
    self.accessModifier = accessModifier
    self.originalName = name
    self.typeName = name.swiftTypeName()
    self.schema = schema
    self.components = components

    if schema.ref != nil {
      throw OpenAPIGeneratorError.unsupported("Component schemas cannot be aliases to $ref yet: \(name).")
    }
  }

  func renderedLines() throws -> [String] {
    if let enumValues = self.schema.enumValues, self.schema.type == "string" {
      return try self.renderedEnumLines(enumValues)
    }
    if self.schema.type == "object" || !self.schema.properties.isEmpty {
      return try self.renderedObjectLines()
    }
    if self.schema.type == "array", let items = self.schema.items {
      let elementType = try items.swiftType(components: self.components, inlineObjectFallback: nil)
        ?? "Data"
      return [
        "\(self.accessModifier) typealias \(self.typeName) = [\(elementType)]"
      ]
    }

    let aliasedType = try self.schema.swiftType(
      components: self.components,
      inlineObjectFallback: "Data"
    ) ?? "Data"
    return [
      "\(self.accessModifier) typealias \(self.typeName) = \(aliasedType)"
    ]
  }

  private func renderedEnumLines(_ values: [String]) throws -> [String] {
    var cases: [(name: String, value: String)] = []
    for value in values {
      cases.append((name: value.swiftIdentifier(), value: value))
    }
    let duplicateCaseNames = Dictionary(grouping: cases, by: \.name)
      .filter { $0.value.count > 1 }
      .map(\.key)
      .sorted()
    guard duplicateCaseNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "\(self.originalName) has enum values that generate duplicate Swift case names: \(duplicateCaseNames.joined(separator: ", "))."
      )
    }

    var lines: [String] = []
    lines.append("\(self.accessModifier) enum \(self.typeName): String, Codable, Sendable {")
    for item in cases {
      lines.append("  case \(item.name) = \(item.value.swiftLiteral)")
    }
    lines.append("}")
    return lines
  }

  private func renderedObjectLines() throws -> [String] {
    let properties = try self.schema.properties.keys.sorted().map { name in
      try GeneratedSchemaProperty(
        name: name,
        schema: self.schema.properties[name]!,
        isRequired: self.schema.required.contains(name),
        components: self.components
      )
    }
    let duplicatePropertyNames = Dictionary(grouping: properties, by: \.swiftName)
      .filter { $0.value.count > 1 }
      .map(\.key)
      .sorted()
    guard duplicatePropertyNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "\(self.originalName) has properties that generate duplicate Swift names: \(duplicatePropertyNames.joined(separator: ", "))."
      )
    }

    var lines: [String] = []
    lines.append("\(self.accessModifier) struct \(self.typeName): Codable, Sendable {")
    if properties.isEmpty {
      lines.append("  \(self.accessModifier) init() {}")
      lines.append("}")
      return lines
    }

    for property in properties {
      lines.append("  \(self.accessModifier) let \(property.swiftName): \(property.swiftType)")
    }

    lines.append("")
    lines.append("  \(self.accessModifier) init(")
    for index in properties.indices {
      lines.append(properties[index].initArgument + (index == properties.indices.last ? "" : ","))
    }
    lines.append("  ) {")
    for property in properties {
      lines.append("    self.\(property.swiftName) = \(property.swiftName)")
    }
    lines.append("  }")

    if properties.contains(where: { $0.swiftName.unescapedSwiftIdentifier != $0.originalName }) {
      lines.append("")
      lines.append("  private enum CodingKeys: String, CodingKey {")
      for property in properties {
        if property.swiftName.unescapedSwiftIdentifier == property.originalName {
          lines.append("    case \(property.swiftName)")
        } else {
          lines.append("    case \(property.swiftName) = \(property.originalName.swiftLiteral)")
        }
      }
      lines.append("  }")
    }

    lines.append("}")
    return lines
  }
}

private struct GeneratedSchemaProperty {
  let originalName: String
  let swiftName: String
  let swiftType: String
  let isRequired: Bool

  init(
    name: String,
    schema: OpenAPISchema,
    isRequired: Bool,
    components: [String: OpenAPISchema]
  ) throws {
    self.originalName = name
    self.swiftName = name.swiftIdentifier()
    self.isRequired = isRequired && !schema.nullable
    guard let type = try schema.swiftType(components: components, inlineObjectFallback: nil) else {
      throw OpenAPIGeneratorError.unsupported("Nested inline object schemas are not generated yet: \(name).")
    }
    self.swiftType = self.isRequired ? type : "\(type)?"
  }

  var initArgument: String {
    "    \(self.swiftName): \(self.swiftType)\(self.isRequired ? "" : " = nil")"
  }
}

private struct GeneratedParameter {
  let originalName: String
  let swiftName: String
  let location: OpenAPIParameterLocation
  let isRequired: Bool
  let baseType: String
  let swiftType: String

  init(_ parameter: OpenAPIParameter, components: [String: OpenAPISchema]) throws {
    guard parameter.location != .cookie else {
      throw OpenAPIGeneratorError.unsupported("Cookie parameters are not generated yet: \(parameter.name).")
    }
    guard parameter.location != .header || parameter.name.isValidHTTPFieldName else {
      throw OpenAPIGeneratorError.invalidDocument("Header parameter has an invalid HTTP field name: \(parameter.name).")
    }

    self.originalName = parameter.name
    self.swiftName = parameter.name.swiftIdentifier()
    self.location = parameter.location
    self.isRequired = parameter.required || parameter.location == .path
    self.baseType = try parameter.schema.swiftType(
      components: components,
      inlineObjectFallback: "String"
    ) ?? "String"
    self.swiftType = self.isRequired ? self.baseType : "\(self.baseType)?"
  }

  func queryItemLines() -> [String] {
    if self.isRequired {
      return ["    items.append(QueryItem(\(self.originalName.swiftLiteral), self.\(self.swiftName)))"]
    }
    return [
      "    if let \(self.swiftName) = self.\(self.swiftName) {",
      "      items.append(QueryItem(\(self.originalName.swiftLiteral), \(self.swiftName)))",
      "    }"
    ]
  }

  func headerLines() -> [String] {
    let headerName = "HTTPField.Name(\(self.originalName.swiftLiteral))!"
    if self.isRequired {
      return ["    headers[\(headerName)] = String(describing: self.\(self.swiftName))"]
    }
    return [
      "    if let \(self.swiftName) = self.\(self.swiftName) {",
      "      headers[\(headerName)] = String(describing: \(self.swiftName))",
      "    }"
    ]
  }
}

private struct OpenAPIDocument: Decodable {
  let openapi: String?
  let components: OpenAPIComponents?
  let paths: [String: OpenAPIPathItem]
}

private struct OpenAPIComponents: Decodable {
  let schemas: [String: OpenAPISchema]

  private enum CodingKeys: String, CodingKey {
    case schemas
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.schemas = try container.decodeIfPresent([String: OpenAPISchema].self, forKey: .schemas) ?? [:]
  }
}

private struct OpenAPIPathItem: Decodable {
  let parameters: [OpenAPIParameter]
  let get: OpenAPIOperation?
  let post: OpenAPIOperation?
  let put: OpenAPIOperation?
  let patch: OpenAPIOperation?
  let delete: OpenAPIOperation?
  let head: OpenAPIOperation?
  let options: OpenAPIOperation?

  private enum CodingKeys: String, CodingKey {
    case parameters
    case get
    case post
    case put
    case patch
    case delete
    case head
    case options
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parameters = try container.decodeIfPresent([OpenAPIParameter].self, forKey: .parameters) ?? []
    self.get = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .get)
    self.post = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .post)
    self.put = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .put)
    self.patch = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .patch)
    self.delete = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .delete)
    self.head = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .head)
    self.options = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .options)
  }

  func operation(for method: HTTPMethodName) -> OpenAPIOperation? {
    switch method {
    case .get:
      return self.get
    case .post:
      return self.post
    case .put:
      return self.put
    case .patch:
      return self.patch
    case .delete:
      return self.delete
    case .head:
      return self.head
    case .options:
      return self.options
    }
  }
}

private struct OpenAPIOperation: Decodable {
  let operationID: String?
  let parameters: [OpenAPIParameter]
  let requestBody: OpenAPIRequestBody?
  let responses: [String: OpenAPIResponse]

  private enum CodingKeys: String, CodingKey {
    case operationID = "operationId"
    case parameters
    case requestBody
    case responses
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.operationID = try container.decodeIfPresent(String.self, forKey: .operationID)
    self.parameters = try container.decodeIfPresent([OpenAPIParameter].self, forKey: .parameters) ?? []
    self.requestBody = try container.decodeIfPresent(OpenAPIRequestBody.self, forKey: .requestBody)
    self.responses = try container.decodeIfPresent([String: OpenAPIResponse].self, forKey: .responses) ?? [:]
  }
}

private struct OpenAPIParameter: Decodable {
  let name: String
  let location: OpenAPIParameterLocation
  let required: Bool
  let schema: OpenAPISchema

  private enum CodingKeys: String, CodingKey {
    case name
    case location = "in"
    case required
    case schema
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(String.self, forKey: .name)
    self.location = try container.decode(OpenAPIParameterLocation.self, forKey: .location)
    self.required = try container.decodeIfPresent(Bool.self, forKey: .required) ?? false
    self.schema = try container.decodeIfPresent(OpenAPISchema.self, forKey: .schema) ?? OpenAPISchema()
  }
}

private enum OpenAPIParameterLocation: String, Decodable {
  case path
  case query
  case header
  case cookie
}

private struct OpenAPIRequestBody: Decodable {
  let content: [String: OpenAPIMediaType]
}

private struct OpenAPIResponse: Decodable {
  let content: [String: OpenAPIMediaType]

  private enum CodingKeys: String, CodingKey {
    case content
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.content = try container.decodeIfPresent([String: OpenAPIMediaType].self, forKey: .content) ?? [:]
  }
}

private struct OpenAPIMediaType: Decodable {
  let schema: OpenAPISchema?
}

private final class OpenAPISchema: Decodable {
  let ref: String?
  let type: String?
  let format: String?
  let nullable: Bool
  let enumValues: [String]?
  let items: OpenAPISchema?
  let properties: [String: OpenAPISchema]
  let required: Set<String>

  init(
    ref: String? = nil,
    type: String? = nil,
    format: String? = nil,
    nullable: Bool = false,
    enumValues: [String]? = nil,
    items: OpenAPISchema? = nil,
    properties: [String: OpenAPISchema] = [:],
    required: Set<String> = []
  ) {
    self.ref = ref
    self.type = type
    self.format = format
    self.nullable = nullable
    self.enumValues = enumValues
    self.items = items
    self.properties = properties
    self.required = required
  }

  private enum CodingKeys: String, CodingKey {
    case ref = "$ref"
    case type
    case format
    case nullable
    case enumValues = "enum"
    case items
    case properties
    case required
  }

  convenience init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    let decodedType: String?
    let nullableFromType: Bool
    if let type = try? container.decode(String.self, forKey: .type) {
      decodedType = type
      nullableFromType = false
    } else if let types = try? container.decode([String].self, forKey: .type) {
      decodedType = types.first { $0 != "null" }
      nullableFromType = types.contains("null")
    } else {
      decodedType = nil
      nullableFromType = false
    }

    self.init(
      ref: try container.decodeIfPresent(String.self, forKey: .ref),
      type: decodedType,
      format: try container.decodeIfPresent(String.self, forKey: .format),
      nullable: (try container.decodeIfPresent(Bool.self, forKey: .nullable) ?? false) || nullableFromType,
      enumValues: try container.decodeIfPresent([String].self, forKey: .enumValues),
      items: try container.decodeIfPresent(OpenAPISchema.self, forKey: .items),
      properties: try container.decodeIfPresent([String: OpenAPISchema].self, forKey: .properties) ?? [:],
      required: Set(try container.decodeIfPresent([String].self, forKey: .required) ?? [])
    )
  }

  func swiftType(
    components: [String: OpenAPISchema],
    inlineObjectFallback: String?
  ) throws -> String? {
    if let ref {
      let componentName = try Self.componentName(forReference: ref)
      guard components[componentName] != nil else {
        throw OpenAPIGeneratorError.invalidDocument("Schema reference was not found: \(ref).")
      }
      return componentName.swiftTypeName()
    }
    if let enumValues, !enumValues.isEmpty, self.type == "string" {
      return "String"
    }
    if self.type == "array" {
      let itemType = try self.items?.swiftType(components: components, inlineObjectFallback: inlineObjectFallback)
        ?? "String"
      return "[\(itemType)]"
    }
    if self.type == "object" || !self.properties.isEmpty {
      return inlineObjectFallback
    }

    switch (self.type, self.format) {
    case ("string", "binary"):
      return "Data"
    case ("string", "date"), ("string", "date-time"):
      return "Date"
    case ("string", "uuid"):
      return "UUID"
    case ("integer", "int64"):
      return "Int64"
    case ("integer", _):
      return "Int"
    case ("number", "float"):
      return "Float"
    case ("number", _):
      return "Double"
    case ("boolean", _):
      return "Bool"
    case ("string", _):
      return "String"
    default:
      return inlineObjectFallback ?? "String"
    }
  }

  private static func componentName(forReference ref: String) throws -> String {
    guard let name = ref.split(separator: "/").last.map(String.init), !name.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument("Unsupported schema reference: \(ref).")
    }
    guard ref.hasPrefix("#/components/schemas/") else {
      throw OpenAPIGeneratorError.unsupported("Only local component schema references are generated: \(ref).")
    }
    return name.swiftTypeName()
  }
}

private enum HTTPMethodName: String, CaseIterable {
  case get
  case post
  case put
  case patch
  case delete
  case head
  case options

  var swiftExpression: String {
    switch self {
    case .get:
      return ".get"
    case .post:
      return ".post"
    case .put:
      return ".put"
    case .patch:
      return ".patch"
    case .delete:
      return ".delete"
    case .head:
      return ".head"
    case .options:
      return ".options"
    }
  }
}

private extension String {
  var swiftLiteral: String {
    String(reflecting: self)
  }

  func swiftIdentifier() -> String {
    let words = self.identifierWords()
    guard let first = words.first else { return "value" }
    let name = ([first.lowercased()] + words.dropFirst().map(\.capitalized)).joined()
    let prefixedName = name.prefixedIfNeededForSwiftIdentifier(prefix: "value")
    guard prefixedName != "self" else { return "selfValue" }
    return SwiftKeywords.escaped(prefixedName)
  }

  func swiftTypeName() -> String {
    let name = self.identifierWords().map(\.capitalized).joined()
    guard !name.isEmpty else { return "GeneratedValue" }
    return SwiftKeywords.escapedTypeName(name.prefixedIfNeededForSwiftIdentifier(prefix: "Generated"))
  }

  var unescapedSwiftIdentifier: String {
    if self.hasPrefix("`"), self.hasSuffix("`") {
      return String(self.dropFirst().dropLast())
    }
    return self
  }

  func identifierWords() -> [String] {
    var words: [String] = []
    var current = ""
    var previousWasLowercaseOrNumber = false

    func flushCurrent() {
      guard !current.isEmpty else { return }
      words.append(current)
      current = ""
    }

    for scalar in self.unicodeScalars {
      guard CharacterSet.alphanumerics.contains(scalar) else {
        flushCurrent()
        previousWasLowercaseOrNumber = false
        continue
      }

      let isUppercase = CharacterSet.uppercaseLetters.contains(scalar)
      if isUppercase, !current.isEmpty, previousWasLowercaseOrNumber {
        flushCurrent()
      }

      current.append(Character(scalar))
      previousWasLowercaseOrNumber = CharacterSet.lowercaseLetters.contains(scalar)
        || CharacterSet.decimalDigits.contains(scalar)
    }

    flushCurrent()
    return words
  }

  func prefixedIfNeededForSwiftIdentifier(prefix: String) -> String {
    guard let first = self.unicodeScalars.first else { return prefix }
    guard !CharacterSet.decimalDigits.contains(first) else {
      return "\(prefix)\(self)"
    }
    return self
  }

  var isValidHTTPFieldName: Bool {
    guard !self.isEmpty else { return false }
    return self.utf8.allSatisfy { byte in
      switch byte {
      case 33, 35...39, 42, 43, 45, 46, 48...57, 65...90, 94...122, 124, 126:
        return true
      default:
        return false
      }
    }
  }
}

private enum SwiftKeywords {
  private static let values: Set<String> = [
    "associatedtype",
    "class",
    "deinit",
    "enum",
    "extension",
    "fileprivate",
    "func",
    "import",
    "init",
    "inout",
    "internal",
    "let",
    "open",
    "operator",
    "private",
    "precedencegroup",
    "protocol",
    "public",
    "rethrows",
    "static",
    "struct",
    "subscript",
    "typealias",
    "var",
    "break",
    "case",
    "continue",
    "default",
    "defer",
    "do",
    "else",
    "fallthrough",
    "for",
    "guard",
    "if",
    "in",
    "repeat",
    "return",
    "switch",
    "where",
    "while",
  ]

  static func escaped(_ name: String) -> String {
    self.values.contains(name) ? "`\(name)`" : name
  }

  static func escapedTypeName(_ name: String) -> String {
    self.values.contains(name) ? "`\(name)`" : name
  }
}
