import Foundation

/// Configuration for generated Comet request source.
public struct OpenAPIGeneratorConfiguration: Sendable, Hashable {
  public var accessModifier: String
  public var imports: [String]
  public var includeHeaderComment: Bool

  public init(
    accessModifier: String = "public",
    imports: [String] = ["Foundation", "HTTPTypes", "Comet"],
    includeHeaderComment: Bool = true
  ) {
    self.accessModifier = accessModifier
    self.imports = imports
    self.includeHeaderComment = includeHeaderComment
  }
}

/// A focused JSON OpenAPI generator for Comet request types.
public struct OpenAPIGenerator: Sendable {
  public init() {}

  public func generate(
    data: Data,
    configuration: OpenAPIGeneratorConfiguration = OpenAPIGeneratorConfiguration()
  ) throws -> String {
    do {
      let document = try JSONDecoder().decode(OpenAPIDocument.self, from: data)
      return try self.generate(document: document, configuration: configuration)
    } catch let error as OpenAPIGeneratorError {
      throw error
    } catch {
      throw OpenAPIGeneratorError.invalidDocument("Unable to decode OpenAPI JSON: \(error)")
    }
  }

  public func generate(
    jsonString: String,
    configuration: OpenAPIGeneratorConfiguration = OpenAPIGeneratorConfiguration()
  ) throws -> String {
    guard let data = jsonString.data(using: .utf8) else {
      throw OpenAPIGeneratorError.invalidDocument("Unable to encode input as UTF-8.")
    }
    return try self.generate(data: data, configuration: configuration)
  }

  private func generate(
    document: OpenAPIDocument,
    configuration: OpenAPIGeneratorConfiguration
  ) throws -> String {
    var operations: [GeneratedOperation] = []

    for path in document.paths.keys.sorted() {
      guard let item = document.paths[path] else { continue }
      for method in HTTPMethodName.allCases {
        guard let operation = item.operation(for: method) else { continue }
        operations.append(
          try GeneratedOperation(
            path: path,
            method: method,
            operation: operation,
            inheritedParameters: item.parameters,
            accessModifier: configuration.accessModifier
          )
        )
      }
    }

    guard !operations.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument("The OpenAPI document did not contain any supported path operations.")
    }

    let duplicateTypeNames = Dictionary(grouping: operations, by: \.typeName)
      .filter { $0.value.count > 1 }
      .map(\.key)
      .sorted()
    guard duplicateTypeNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "Multiple operations generate duplicate request type names: \(duplicateTypeNames.joined(separator: ", "))."
      )
    }

    var lines: [String] = []
    if configuration.includeHeaderComment {
      lines.append("// Generated by comet-openapi-generate. Edit the OpenAPI source instead of this file.")
      lines.append("")
    }

    for module in configuration.imports {
      lines.append("import \(module)")
    }
    lines.append("")

    for (index, operation) in operations.enumerated() {
      if index > 0 {
        lines.append("")
      }
      lines.append(contentsOf: operation.renderedLines())
    }

    return lines.joined(separator: "\n") + "\n"
  }
}

/// Errors emitted by the OpenAPI generator.
public struct OpenAPIGeneratorError: Error, Sendable, CustomStringConvertible, Equatable {
  public var message: String

  public init(_ message: String) {
    self.message = message
  }

  public static func invalidDocument(_ message: String) -> Self {
    Self(message)
  }

  public static func unsupported(_ message: String) -> Self {
    Self("Unsupported OpenAPI feature: \(message)")
  }

  public var description: String {
    self.message
  }
}

private struct GeneratedOperation {
  let accessModifier: String
  let typeName: String
  let genericBodyType: Bool
  let method: HTTPMethodName
  let pathExpression: String
  let parameters: [GeneratedParameter]
  let queryParameters: [GeneratedParameter]
  let headerParameters: [GeneratedParameter]
  let hasJSONBody: Bool
  let responseType: String
  let responseSerializer: String
  let hasTypedErrorResponse: Bool
  let operationID: String

  init(
    path: String,
    method: HTTPMethodName,
    operation: OpenAPIOperation,
    inheritedParameters: [OpenAPIParameter],
    accessModifier: String
  ) throws {
    self.accessModifier = accessModifier
    self.method = method
    self.operationID = operation.operationID ?? "\(method.rawValue)-\(path)"
    self.typeName = Self.typeName(operationID: operation.operationID, method: method, path: path)

    let mergedParameters = Self.mergedParameters(
      inheritedParameters,
      overridingWith: operation.parameters
    )
    let parameters = try mergedParameters.map { try GeneratedParameter($0) }
    let duplicateSwiftParameterNames = Dictionary(grouping: parameters, by: \.swiftName)
      .filter { $0.value.count > 1 }
      .map(\.key)
      .sorted()
    guard duplicateSwiftParameterNames.isEmpty else {
      throw OpenAPIGeneratorError.invalidDocument(
        "\(self.operationID) has parameters that generate duplicate Swift names: \(duplicateSwiftParameterNames.joined(separator: ", "))."
      )
    }
    self.parameters = parameters
    self.queryParameters = parameters.filter { $0.location == .query }
    self.headerParameters = parameters.filter { $0.location == .header }
    self.pathExpression = try Self.pathExpression(path: path, parameters: parameters)

    if let requestBody = operation.requestBody {
      guard requestBody.content.keys.contains("application/json") else {
        throw OpenAPIGeneratorError.unsupported(
          "\(self.operationID) declares a request body without application/json content."
        )
      }
      self.hasJSONBody = true
      self.genericBodyType = true
    } else {
      self.hasJSONBody = false
      self.genericBodyType = false
    }

    let response = Self.successResponse(from: operation.responses)
    self.responseType = response.type
    self.responseSerializer = response.serializer
    self.hasTypedErrorResponse = operation.responses.contains { status, _ in
      guard let code = Int(status) else { return status == "default" }
      return !(200..<300).contains(code)
    }
  }

  func renderedLines() -> [String] {
    var lines: [String] = []
    let protocolName = self.hasTypedErrorResponse ? "APIRequestWithErrorResponse" : "APIRequest"
    let generic = self.genericBodyType ? "<Body: Encodable & Sendable>" : ""
    lines.append("\(self.accessModifier) struct \(self.typeName)\(generic): \(protocolName) {")
    lines.append("  \(self.accessModifier) typealias Response = \(self.responseType)")
    if self.hasTypedErrorResponse {
      lines.append("  \(self.accessModifier) typealias ErrorResponse = Data")
    }
    lines.append("")

    for parameter in self.parameters {
      lines.append("  \(self.accessModifier) let \(parameter.swiftName): \(parameter.swiftType)")
    }
    if self.hasJSONBody {
      lines.append("  \(self.accessModifier) let bodyPayload: Body")
    }

    if !self.parameters.isEmpty || self.hasJSONBody {
      lines.append("")
      lines.append(contentsOf: self.initLines())
    } else {
      lines.append("")
      lines.append("  \(self.accessModifier) init() {}")
    }

    lines.append("")
    lines.append("  \(self.accessModifier) var path: Path {")
    lines.append("    \(self.pathExpression)")
    lines.append("  }")
    lines.append("")
    lines.append("  \(self.accessModifier) let method: HTTPMethod = \(self.method.swiftExpression)")

    if !self.queryParameters.isEmpty {
      lines.append("")
      lines.append("  \(self.accessModifier) var queryItems: [QueryItem] {")
      lines.append("    var items: [QueryItem] = []")
      for parameter in self.queryParameters {
        lines.append(contentsOf: parameter.queryItemLines())
      }
      lines.append("    return items")
      lines.append("  }")
    }

    if !self.headerParameters.isEmpty {
      lines.append("")
      lines.append("  \(self.accessModifier) var headers: HTTPFields {")
      lines.append("    var headers = HTTPFields()")
      for parameter in self.headerParameters {
        lines.append(contentsOf: parameter.headerLines())
      }
      lines.append("    return headers")
      lines.append("  }")
    }

    if self.hasJSONBody {
      lines.append("")
      lines.append("  \(self.accessModifier) var body: HTTPBody {")
      lines.append("    .json(self.bodyPayload)")
      lines.append("  }")
    }

    lines.append("")
    lines.append("  \(self.accessModifier) var options: RequestOptions {")
    lines.append("    RequestOptions(")
    lines.append("      metadata: RequestMetadata(operationID: \(self.operationID.swiftLiteral))")
    lines.append("    )")
    lines.append("  }")
    lines.append("")
    lines.append("  \(self.accessModifier) let responseSerializer: ResponseSerializer<\(self.responseType)> = \(self.responseSerializer)")

    if self.hasTypedErrorResponse {
      lines.append("  \(self.accessModifier) let errorResponseSerializer: ErrorResponseSerializer<Data> = .data")
    }

    lines.append("}")
    return lines
  }

  private func initLines() -> [String] {
    var lines: [String] = []
    lines.append("  \(self.accessModifier) init(")
    var arguments = self.parameters.map { parameter in
      "    \(parameter.swiftName): \(parameter.swiftType)"
    }
    if self.hasJSONBody {
      arguments.append("    bodyPayload: Body")
    }
    for index in arguments.indices {
      lines.append(arguments[index] + (index == arguments.indices.last ? "" : ","))
    }
    lines.append("  ) {")
    for parameter in self.parameters {
      lines.append("    self.\(parameter.swiftName) = \(parameter.swiftName)")
    }
    if self.hasJSONBody {
      lines.append("    self.bodyPayload = bodyPayload")
    }
    lines.append("  }")
    return lines
  }

  private static func typeName(
    operationID: String?,
    method: HTTPMethodName,
    path: String
  ) -> String {
    let raw = operationID ?? "\(method.rawValue) \(path)"
    let name = raw.identifierWords().map(\.capitalized).joined()
    guard !name.isEmpty else { return "GeneratedRequest" }
    return "\(name.prefixedIfNeededForSwiftIdentifier(prefix: "Generated"))Request"
  }

  private static func pathExpression(
    path: String,
    parameters: [GeneratedParameter]
  ) throws -> String {
    let pathParameters = Dictionary(uniqueKeysWithValues: parameters.filter { $0.location == .path }.map { ($0.originalName, $0) })
    let segments = path
      .split(separator: "/")
      .map(String.init)
      .filter { !$0.isEmpty }

    guard !segments.isEmpty else { return "Path(\"\")" }

    var expressions: [String] = []
    for segment in segments {
      if segment.hasPrefix("{"), segment.hasSuffix("}") {
        let rawName = String(segment.dropFirst().dropLast())
        guard let parameter = pathParameters[rawName] else {
          throw OpenAPIGeneratorError.invalidDocument("Path parameter {\(rawName)} is missing from the operation parameters.")
        }
        expressions.append("self.\(parameter.swiftName)")
      } else {
        expressions.append(segment.swiftLiteral)
      }
    }

    let first = expressions.removeFirst()
    let base = first.hasPrefix("\"") ? first : "Path(\"\") / \(first)"
    guard !expressions.isEmpty else { return first.hasPrefix("\"") ? base : base }
    return ([base] + expressions).joined(separator: " / ")
  }

  private static func successResponse(from responses: [String: OpenAPIResponse]) -> (type: String, serializer: String) {
    let success = responses
      .compactMap { status, response -> (Int, OpenAPIResponse)? in
        guard let code = Int(status), (200..<300).contains(code) else { return nil }
        return (code, response)
      }
      .sorted { $0.0 < $1.0 }
      .first

    guard let success else {
      return ("Data", ".data")
    }

    if success.0 == 204 || success.1.content.isEmpty {
      return ("EmptyResponse", ".empty")
    }

    if success.1.content.keys.contains("text/plain") {
      return ("String", ".string()")
    }

    return ("Data", ".data")
  }

  private static func mergedParameters(
    _ inherited: [OpenAPIParameter],
    overridingWith operationParameters: [OpenAPIParameter]
  ) -> [OpenAPIParameter] {
    var parameters = inherited
    for operationParameter in operationParameters {
      if let index = parameters.firstIndex(where: {
        $0.name == operationParameter.name && $0.location == operationParameter.location
      }) {
        parameters[index] = operationParameter
      } else {
        parameters.append(operationParameter)
      }
    }
    return parameters
  }
}

private struct GeneratedParameter {
  let originalName: String
  let swiftName: String
  let location: OpenAPIParameterLocation
  let isRequired: Bool
  let baseType: String
  let swiftType: String

  init(_ parameter: OpenAPIParameter) throws {
    guard parameter.location != .cookie else {
      throw OpenAPIGeneratorError.unsupported("Cookie parameters are not generated yet: \(parameter.name).")
    }
    guard parameter.location != .header || parameter.name.isValidHTTPFieldName else {
      throw OpenAPIGeneratorError.invalidDocument("Header parameter has an invalid HTTP field name: \(parameter.name).")
    }

    self.originalName = parameter.name
    self.swiftName = parameter.name.swiftIdentifier()
    self.location = parameter.location
    self.isRequired = parameter.required || parameter.location == .path
    self.baseType = parameter.schema.swiftType
    self.swiftType = self.isRequired ? self.baseType : "\(self.baseType)?"
  }

  func queryItemLines() -> [String] {
    if self.isRequired {
      return ["    items.append(QueryItem(\(self.originalName.swiftLiteral), self.\(self.swiftName)))"]
    }
    return [
      "    if let \(self.swiftName) = self.\(self.swiftName) {",
      "      items.append(QueryItem(\(self.originalName.swiftLiteral), \(self.swiftName)))",
      "    }"
    ]
  }

  func headerLines() -> [String] {
    let headerName = "HTTPField.Name(\(self.originalName.swiftLiteral))!"
    if self.isRequired {
      return ["    headers[\(headerName)] = String(describing: self.\(self.swiftName))"]
    }
    return [
      "    if let \(self.swiftName) = self.\(self.swiftName) {",
      "      headers[\(headerName)] = String(describing: \(self.swiftName))",
      "    }"
    ]
  }
}

private struct OpenAPIDocument: Decodable {
  let openapi: String?
  let paths: [String: OpenAPIPathItem]
}

private struct OpenAPIPathItem: Decodable {
  let parameters: [OpenAPIParameter]
  let get: OpenAPIOperation?
  let post: OpenAPIOperation?
  let put: OpenAPIOperation?
  let patch: OpenAPIOperation?
  let delete: OpenAPIOperation?
  let head: OpenAPIOperation?
  let options: OpenAPIOperation?

  private enum CodingKeys: String, CodingKey {
    case parameters
    case get
    case post
    case put
    case patch
    case delete
    case head
    case options
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parameters = try container.decodeIfPresent([OpenAPIParameter].self, forKey: .parameters) ?? []
    self.get = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .get)
    self.post = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .post)
    self.put = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .put)
    self.patch = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .patch)
    self.delete = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .delete)
    self.head = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .head)
    self.options = try container.decodeIfPresent(OpenAPIOperation.self, forKey: .options)
  }

  func operation(for method: HTTPMethodName) -> OpenAPIOperation? {
    switch method {
    case .get:
      return self.get
    case .post:
      return self.post
    case .put:
      return self.put
    case .patch:
      return self.patch
    case .delete:
      return self.delete
    case .head:
      return self.head
    case .options:
      return self.options
    }
  }
}

private struct OpenAPIOperation: Decodable {
  let operationID: String?
  let parameters: [OpenAPIParameter]
  let requestBody: OpenAPIRequestBody?
  let responses: [String: OpenAPIResponse]

  private enum CodingKeys: String, CodingKey {
    case operationID = "operationId"
    case parameters
    case requestBody
    case responses
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.operationID = try container.decodeIfPresent(String.self, forKey: .operationID)
    self.parameters = try container.decodeIfPresent([OpenAPIParameter].self, forKey: .parameters) ?? []
    self.requestBody = try container.decodeIfPresent(OpenAPIRequestBody.self, forKey: .requestBody)
    self.responses = try container.decodeIfPresent([String: OpenAPIResponse].self, forKey: .responses) ?? [:]
  }
}

private struct OpenAPIParameter: Decodable {
  let name: String
  let location: OpenAPIParameterLocation
  let required: Bool
  let schema: OpenAPISchema

  private enum CodingKeys: String, CodingKey {
    case name
    case location = "in"
    case required
    case schema
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(String.self, forKey: .name)
    self.location = try container.decode(OpenAPIParameterLocation.self, forKey: .location)
    self.required = try container.decodeIfPresent(Bool.self, forKey: .required) ?? false
    self.schema = try container.decodeIfPresent(OpenAPISchema.self, forKey: .schema) ?? OpenAPISchema()
  }
}

private enum OpenAPIParameterLocation: String, Decodable {
  case path
  case query
  case header
  case cookie
}

private struct OpenAPIRequestBody: Decodable {
  let content: [String: OpenAPIMediaType]
}

private struct OpenAPIResponse: Decodable {
  let content: [String: OpenAPIMediaType]

  private enum CodingKeys: String, CodingKey {
    case content
  }

  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.content = try container.decodeIfPresent([String: OpenAPIMediaType].self, forKey: .content) ?? [:]
  }
}

private struct OpenAPIMediaType: Decodable {
  let schema: OpenAPISchema?
}

private struct OpenAPISchema: Decodable {
  let type: String?
  let format: String?

  init(type: String? = nil, format: String? = nil) {
    self.type = type
    self.format = format
  }

  var swiftType: String {
    switch (self.type, self.format) {
    case ("integer", "int64"):
      return "Int64"
    case ("integer", _):
      return "Int"
    case ("number", "float"):
      return "Float"
    case ("number", _):
      return "Double"
    case ("boolean", _):
      return "Bool"
    case ("string", _):
      return "String"
    default:
      return "String"
    }
  }
}

private enum HTTPMethodName: String, CaseIterable {
  case get
  case post
  case put
  case patch
  case delete
  case head
  case options

  var swiftExpression: String {
    switch self {
    case .get:
      return ".get"
    case .post:
      return ".post"
    case .put:
      return ".put"
    case .patch:
      return ".patch"
    case .delete:
      return ".delete"
    case .head:
      return ".head"
    case .options:
      return ".options"
    }
  }
}

private extension String {
  var swiftLiteral: String {
    String(reflecting: self)
  }

  func swiftIdentifier() -> String {
    let words = self.identifierWords()
    guard let first = words.first else { return "value" }
    let name = ([first.lowercased()] + words.dropFirst().map(\.capitalized)).joined()
    let prefixedName = name.prefixedIfNeededForSwiftIdentifier(prefix: "value")
    guard prefixedName != "self" else { return "selfValue" }
    return SwiftKeywords.escaped(prefixedName)
  }

  func identifierWords() -> [String] {
    var words: [String] = []
    var current = ""
    var previousWasLowercaseOrNumber = false

    func flushCurrent() {
      guard !current.isEmpty else { return }
      words.append(current)
      current = ""
    }

    for scalar in self.unicodeScalars {
      guard CharacterSet.alphanumerics.contains(scalar) else {
        flushCurrent()
        previousWasLowercaseOrNumber = false
        continue
      }

      let isUppercase = CharacterSet.uppercaseLetters.contains(scalar)
      if isUppercase, !current.isEmpty, previousWasLowercaseOrNumber {
        flushCurrent()
      }

      current.append(Character(scalar))
      previousWasLowercaseOrNumber = CharacterSet.lowercaseLetters.contains(scalar)
        || CharacterSet.decimalDigits.contains(scalar)
    }

    flushCurrent()
    return words
  }

  func prefixedIfNeededForSwiftIdentifier(prefix: String) -> String {
    guard let first = self.unicodeScalars.first else { return prefix }
    guard !CharacterSet.decimalDigits.contains(first) else {
      return "\(prefix)\(self)"
    }
    return self
  }

  var isValidHTTPFieldName: Bool {
    guard !self.isEmpty else { return false }
    return self.utf8.allSatisfy { byte in
      switch byte {
      case 33, 35...39, 42, 43, 45, 46, 48...57, 65...90, 94...122, 124, 126:
        return true
      default:
        return false
      }
    }
  }
}

private enum SwiftKeywords {
  private static let values: Set<String> = [
    "associatedtype",
    "class",
    "deinit",
    "enum",
    "extension",
    "fileprivate",
    "func",
    "import",
    "init",
    "inout",
    "internal",
    "let",
    "open",
    "operator",
    "private",
    "precedencegroup",
    "protocol",
    "public",
    "rethrows",
    "static",
    "struct",
    "subscript",
    "typealias",
    "var",
    "break",
    "case",
    "continue",
    "default",
    "defer",
    "do",
    "else",
    "fallthrough",
    "for",
    "guard",
    "if",
    "in",
    "repeat",
    "return",
    "switch",
    "where",
    "while",
  ]

  static func escaped(_ name: String) -> String {
    self.values.contains(name) ? "`\(name)`" : name
  }
}
